stages:
  - pre-build
  - pre-check
  - test
  - publish

#
# PRE-BUILD
#
build_image_next:
  stage: pre-build
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - npm run bump:develop
    - docker pull node
    - docker build --no-cache
        --build-arg NODE_ENV="develop"
        --build-arg CLIENT_TAG="next"
        -t "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}-dev" .
    - docker push "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}-dev"
    - docker build --no-cache
        --build-arg NODE_ENV="production"
        --build-arg CLIENT_TAG="next"
        -t "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}" .
    - docker push "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}"
  except:
    - master

build_image:
  stage: pre-build
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - npm run bump:production
    - docker pull node
    - docker build --no-cache
        --build-arg NODE_ENV="develop"
        -t "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}-dev" .
    - docker push "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}-dev"
    - docker build --no-cache
        --build-arg NODE_ENV="production"
        -t "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}" .
    - docker push "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}"
  only:
    - master


#
# PRE-CHECK
#
check_lint:
  stage: pre-check
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - docker pull "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}-dev"
    - docker run --rm "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}-dev" npm run check

visualize:
  stage: pre-check
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - docker pull "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}-dev"
    - mkdir ./code-visualization
    - docker run --rm -v "$(pwd)/code-visualization:/usr/local/lib/node_modules/@dwimm/server/code-visualization"
        -u "$UID:$GID" "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}-dev" npm run visualize
    - rm -rf /var/docker/static/dwimm/server/plato/*
    - mv ./code-visualization/* /var/docker/static/dwimm/server/plato/


#
# PUBLISH
#
build_image_next_arm:
  stage: publish
  tags:
    - docker-host
    - arm
    - ssh
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - npm run bump:develop
    - docker pull arm32v7/node
    - docker build --no-cache
        --build-arg NODE_ENV="develop"
        --build-arg CLIENT_TAG="next"
        -f ./Dockerfile.arm
        -t "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}-arm-dev" .
    - docker push "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}-arm-dev"
    - docker build --no-cache
        --build-arg NODE_ENV="production"
        --build-arg CLIENT_TAG="next"
        -f ./Dockerfile.arm
        -t "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}-arm" .
    - docker push "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}-arm"
    - docker tag "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}-arm" "sebbo2002/dwimm-server-beta:next-arm"
    - docker push "sebbo2002/dwimm-server-beta:next-arm"
  except:
    - master

build_image_arm:
  stage: build
  tags:
    - docker-host
    - arm
    - ssh
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - npm run bump:production
    - docker pull arm32v7/node
    - docker build --no-cache
        --build-arg NODE_ENV="develop"
        -f ./Dockerfile.arm
        -t "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}-arm-dev" .
    - docker push "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}-arm-dev"
    - docker build --no-cache
        --build-arg NODE_ENV="production"
        -f ./Dockerfile.arm
        -t "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}-arm" .
    - docker push "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}-arm"
    - docker tag "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}" "sebbo2002/dwimm-server-beta:arm"
    - docker push "sebbo2002/dwimm-server-beta:arm"
  only:
    - master


publish_github:
  stage: pre-build
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - git push "https://${GITHUB_AUTH}@github.com/sebbo2002/dwimm-server.git" --all
    - git push "https://${GITHUB_AUTH}@github.com/sebbo2002/dwimm-server.git" --tags


publish_npm_next:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - node -v
    - yarn -v
    - yarn install
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.sebbo.net
    - docker pull "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}"
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - npm run bump:develop
    - echo $(docker run --rm "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}" cat ./package.json | jq '.version' -rce)
    - npm publish --tag "next"
  only:
    - develop


publish_dockerhub_beta_next:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker pull "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}"
    - docker tag "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}" "sebbo2002/dwimm-server-beta:next"
    - docker push "sebbo2002/dwimm-server-beta:next"
  only:
    - develop

publish_dockerhub_beta:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker pull "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}"
    - docker tag "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}" "sebbo2002/dwimm-server-beta"
    - docker push "sebbo2002/dwimm-server-beta"
  only:
    - master

private-deployment:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  environment:
    name: dwimm.sebbo.net
    url: https://dwimm.sebbo.net/
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - docker pull "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}"
    - docker stop "dwimm" || true
    - docker rm "dwimm" || true
    - docker create --restart "always" --name="dwimm"
        --link mariadb:db
        -v "/etc/timezone:/etc/timezone:ro" -v "/etc/localtime:/etc/localtime:ro"
        -e "DATABASE=${DEPLOYMENT_DATABASE}"
        -p 127.0.0.1:10060:8080
        "docker.sebbo.net/dwimm/server:${CI_COMMIT_SHA}"
    - docker start dwimm
  when: manual
  only:
    - develop
    - master
