version: "3.7"
services:
  database:
    image: "mariadb:latest"
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: "**********"
      MYSQL_USER: "ubud"
      MYSQL_PASSWORD: "**********"
      MYSQL_DATABASE: "ubud"
#    volumes:
#      - /path/to/persist:/var/lib/mysql

  ubud:
    image: "ubud/server:next"
    restart: "always"
    environment:
      DATABASE: "mysql://ubud:**********@database/ubud"
    depends_on:
      - "database"
    expose:
      - "8080"
    ports:
      - "127.0.0.1:8080:8080"
